export const dummyData = [
  {
    "id": 53528,
    "url": "https://yts.mx/movies/mickey-hardaway-2023",
    "imdb_code": "tt16977014",
    "title": "Mickey Hardaway",
    "title_english": "Mickey Hardaway",
    "title_long": "Mickey Hardaway (2023)",
    "slug": "mickey-hardaway-2023",
    "year": 2023,
    "rating": 8.7,
    "runtime": 106,
    "genres": [
      "Drama"
    ],
    "summary": "A young sketch artist agrees to a in-house therapy session with a well renowned psychiatrist as his life begins sprawling out of control after years of physical and verbal abuse has finally taken a toll on him.",
    "description_full": "A young sketch artist agrees to a in-house therapy session with a well renowned psychiatrist as his life begins sprawling out of control after years of physical and verbal abuse has finally taken a toll on him.",
    "synopsis": "A young sketch artist agrees to a in-house therapy session with a well renowned psychiatrist as his life begins sprawling out of control after years of physical and verbal abuse has finally taken a toll on him.",
    "yt_trailer_code": "Mi1u1Ws4KRI",
    "language": "en",
    "mpa_rating": "",
    "background_image": "https://yts.mx/assets/images/movies/mickey_hardaway_2023/background.jpg",
    "background_image_original": "https://yts.mx/assets/images/movies/mickey_hardaway_2023/background.jpg",
    "small_cover_image": "https://yts.mx/assets/images/movies/mickey_hardaway_2023/small-cover.jpg",
    "medium_cover_image": "https://yts.mx/assets/images/movies/mickey_hardaway_2023/medium-cover.jpg",
    "large_cover_image": "https://yts.mx/assets/images/movies/mickey_hardaway_2023/large-cover.jpg",
    "state": "ok",
    "torrents": [
      {
        "url": "https://yts.mx/torrent/download/00472CE65ABC221A1C8E961B5BB841D9FF9F7DF1",
        "hash": "00472CE65ABC221A1C8E961B5BB841D9FF9F7DF1",
        "quality": "720p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 14,
        "peers": 1,
        "size": "964.32 MB",
        "size_bytes": 1011162808,
        "date_uploaded": "2023-07-30 17:10:29",
        "date_uploaded_unix": 1690729829
      },
      {
        "url": "https://yts.mx/torrent/download/4979C5C3346E79A2C5278E4CAE700907A8434455",
        "hash": "4979C5C3346E79A2C5278E4CAE700907A8434455",
        "quality": "1080p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 16,
        "peers": 2,
        "size": "1.75 GB",
        "size_bytes": 1879048192,
        "date_uploaded": "2023-07-30 18:25:43",
        "date_uploaded_unix": 1690734343
      },
      {
        "url": "https://yts.mx/torrent/download/CAD4CE1B5AEFA6FE25751EAB4431258DDAAD1DE9",
        "hash": "CAD4CE1B5AEFA6FE25751EAB4431258DDAAD1DE9",
        "quality": "1080p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x265",
        "bit_depth": "10",
        "audio_channels": "2.0",
        "seeds": 6,
        "peers": 0,
        "size": "1.57 GB",
        "size_bytes": 1685774664,
        "date_uploaded": "2023-08-04 12:01:53",
        "date_uploaded_unix": 1691143313
      }
    ],
    "date_uploaded": "2023-07-30 17:10:29",
    "date_uploaded_unix": 1690729829
  },
  {
    "id": 51535,
    "url": "https://yts.mx/movies/trials-to-triumph-the-documentary-2023",
    "imdb_code": "tt26491924",
    "title": "Trials to Triumph: The Documentary",
    "title_english": "Trials to Triumph: The Documentary",
    "title_long": "Trials to Triumph: The Documentary (2023)",
    "slug": "trials-to-triumph-the-documentary-2023",
    "year": 2023,
    "rating": 8.5,
    "runtime": 0,
    "genres": [
      "Documentary"
    ],
    "summary": "Follows the meteoric career of Freddie Stevenson, from his fall and struggle to revival, with the redemption stories of Maurice Benard, former pro football player Delvin Breaux, motivational speaker Tony Gaskins and others.",
    "description_full": "Follows the meteoric career of Freddie Stevenson, from his fall and struggle to revival, with the redemption stories of Maurice Benard, former pro football player Delvin Breaux, motivational speaker Tony Gaskins and others.",
    "synopsis": "Follows the meteoric career of Freddie Stevenson, from his fall and struggle to revival, with the redemption stories of Maurice Benard, former pro football player Delvin Breaux, motivational speaker Tony Gaskins and others.",
    "yt_trailer_code": "kgi_OyCn9nw",
    "language": "en",
    "mpa_rating": "",
    "background_image": "https://yts.mx/assets/images/movies/trials_to_triumph_the_documentary_2023/background.jpg",
    "background_image_original": "https://yts.mx/assets/images/movies/trials_to_triumph_the_documentary_2023/background.jpg",
    "small_cover_image": "https://yts.mx/assets/images/movies/trials_to_triumph_the_documentary_2023/small-cover.jpg",
    "medium_cover_image": "https://yts.mx/assets/images/movies/trials_to_triumph_the_documentary_2023/medium-cover.jpg",
    "large_cover_image": "https://yts.mx/assets/images/movies/trials_to_triumph_the_documentary_2023/large-cover.jpg",
    "state": "ok",
    "torrents": [
      {
        "url": "https://yts.mx/torrent/download/BCFE66E147C4C5A2D812464A52AFE9167757BBC5",
        "hash": "BCFE66E147C4C5A2D812464A52AFE9167757BBC5",
        "quality": "720p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 2,
        "peers": 1,
        "size": "865.97 MB",
        "size_bytes": 908035359,
        "date_uploaded": "2023-05-08 02:35:32",
        "date_uploaded_unix": 1683506132
      },
      {
        "url": "https://yts.mx/torrent/download/C91245672001988BE80CF8CC736401617CBAC955",
        "hash": "C91245672001988BE80CF8CC736401617CBAC955",
        "quality": "1080p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 4,
        "peers": 1,
        "size": "1.57 GB",
        "size_bytes": 1685774664,
        "date_uploaded": "2023-05-08 03:46:52",
        "date_uploaded_unix": 1683510412
      }
    ],
    "date_uploaded": "2023-05-08 02:35:32",
    "date_uploaded_unix": 1683506132
  },
  {
    "id": 52585,
    "url": "https://yts.mx/movies/spider-man-across-the-spider-verse-2023",
    "imdb_code": "tt9362722",
    "title": "Spider-Man: Across the Spider-Verse",
    "title_english": "Spider-Man: Across the Spider-Verse",
    "title_long": "Spider-Man: Across the Spider-Verse (2023)",
    "slug": "spider-man-across-the-spider-verse-2023",
    "year": 2023,
    "rating": 8.8,
    "runtime": 140,
    "genres": [
      "Action",
      "Adventure",
      "Animation",
      "Family",
      "Fantasy",
      "Sci-Fi"
    ],
    "summary": "Miles Morales returns for the next chapter of the Oscar®-winning Spider-Verse saga, an epic adventure that will transport Brooklyn's full-time, friendly neighborhood Spider-Man across the Multiverse to join forces with Gwen Stacy and a new team of Spider-People to face off with a villain more powerful than anything they have ever encountered.—Sony Pictures",
    "description_full": "Miles Morales returns for the next chapter of the Oscar®-winning Spider-Verse saga, an epic adventure that will transport Brooklyn's full-time, friendly neighborhood Spider-Man across the Multiverse to join forces with Gwen Stacy and a new team of Spider-People to face off with a villain more powerful than anything they have ever encountered.—Sony Pictures",
    "synopsis": "Miles Morales returns for the next chapter of the Oscar®-winning Spider-Verse saga, an epic adventure that will transport Brooklyn's full-time, friendly neighborhood Spider-Man across the Multiverse to join forces with Gwen Stacy and a new team of Spider-People to face off with a villain more powerful than anything they have ever encountered.—Sony Pictures",
    "yt_trailer_code": "yFrxzaBLDQM",
    "language": "en",
    "mpa_rating": "PG",
    "background_image": "https://yts.mx/assets/images/movies/spider_man_across_the_spider_verse_2023/background.jpg",
    "background_image_original": "https://yts.mx/assets/images/movies/spider_man_across_the_spider_verse_2023/background.jpg",
    "small_cover_image": "https://yts.mx/assets/images/movies/spider_man_across_the_spider_verse_2023/small-cover.jpg",
    "medium_cover_image": "https://yts.mx/assets/images/movies/spider_man_across_the_spider_verse_2023/medium-cover.jpg",
    "large_cover_image": "https://yts.mx/assets/images/movies/spider_man_across_the_spider_verse_2023/large-cover.jpg",
    "state": "ok",
    "torrents": [
      {
        "url": "https://yts.mx/torrent/download/86459097095BE9314C16FE60694212842805BA56",
        "hash": "86459097095BE9314C16FE60694212842805BA56",
        "quality": "720p",
        "type": "bluray",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 490,
        "peers": 90,
        "size": "1.26 GB",
        "size_bytes": 1352914698,
        "date_uploaded": "2023-08-30 04:41:35",
        "date_uploaded_unix": 1693363295
      },
      {
        "url": "https://yts.mx/torrent/download/E4E3A61DE8B35CACE46500FE7DE50B1C58B80C71",
        "hash": "E4E3A61DE8B35CACE46500FE7DE50B1C58B80C71",
        "quality": "1080p",
        "type": "bluray",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "5.1",
        "seeds": 773,
        "peers": 125,
        "size": "2.59 GB",
        "size_bytes": 2780991324,
        "date_uploaded": "2023-08-30 06:04:51",
        "date_uploaded_unix": 1693368291
      },
      {
        "url": "https://yts.mx/torrent/download/8E7A10B30DAF286C3982BF2DDC1FEAFD78A34513",
        "hash": "8E7A10B30DAF286C3982BF2DDC1FEAFD78A34513",
        "quality": "720p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 1920,
        "peers": 280,
        "size": "1.26 GB",
        "size_bytes": 1352914698,
        "date_uploaded": "2023-08-07 17:28:22",
        "date_uploaded_unix": 1691422102
      },
      {
        "url": "https://yts.mx/torrent/download/22B41B97F077F0D960AC60241B7423AD40420BDD",
        "hash": "22B41B97F077F0D960AC60241B7423AD40420BDD",
        "quality": "1080p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "5.1",
        "seeds": 4205,
        "peers": 1115,
        "size": "2.59 GB",
        "size_bytes": 2780991324,
        "date_uploaded": "2023-08-07 18:49:33",
        "date_uploaded_unix": 1691426973
      },
      {
        "url": "https://yts.mx/torrent/download/559C85A6FB02CD59AAE5B381A0028EF6148FE4D9",
        "hash": "559C85A6FB02CD59AAE5B381A0028EF6148FE4D9",
        "quality": "1080p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x265",
        "bit_depth": "10",
        "audio_channels": "5.1",
        "seeds": 1400,
        "peers": 177,
        "size": "2.34 GB",
        "size_bytes": 2512555868,
        "date_uploaded": "2023-08-08 03:04:28",
        "date_uploaded_unix": 1691456668
      },
      {
        "url": "https://yts.mx/torrent/download/44F5C938FF3B2D49C3C8B74E57039160E8DD1046",
        "hash": "44F5C938FF3B2D49C3C8B74E57039160E8DD1046",
        "quality": "2160p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x265",
        "bit_depth": "10",
        "audio_channels": "5.1",
        "seeds": 1535,
        "peers": 601,
        "size": "6.25 GB",
        "size_bytes": 6710886400,
        "date_uploaded": "2023-08-08 23:28:47",
        "date_uploaded_unix": 1691530127
      }
    ],
    "date_uploaded": "2023-08-07 17:28:22",
    "date_uploaded_unix": 1691422102
  },
  {
    "id": 52762,
    "url": "https://yts.mx/movies/maharashtra-shaheer-2023",
    "imdb_code": "tt15554876",
    "title": "Maharashtra Shaheer",
    "title_english": "Maharashtra Shaheer",
    "title_long": "Maharashtra Shaheer (2023)",
    "slug": "maharashtra-shaheer-2023",
    "year": 2023,
    "rating": 8.6,
    "runtime": 0,
    "genres": [
      "Action",
      "Biography"
    ],
    "summary": "Shahir Krushnarao Sable began his journey as a simple folk singer, and reached great heights when he used his music for so much more. When state of Maharashtra was formed, it was Shahir Sable's immortal voice that took the anthem 'Jai Jai Maharashtra Maza' to every household. This is his story.—Everest",
    "description_full": "Shahir Krushnarao Sable began his journey as a simple folk singer, and reached great heights when he used his music for so much more. When state of Maharashtra was formed, it was Shahir Sable's immortal voice that took the anthem 'Jai Jai Maharashtra Maza' to every household. This is his story.—Everest",
    "synopsis": "Shahir Krushnarao Sable began his journey as a simple folk singer, and reached great heights when he used his music for so much more. When state of Maharashtra was formed, it was Shahir Sable's immortal voice that took the anthem 'Jai Jai Maharashtra Maza' to every household. This is his story.—Everest",
    "yt_trailer_code": "RD_drMIqFwM",
    "language": "mr",
    "mpa_rating": "",
    "background_image": "https://yts.mx/assets/images/movies/maharashtra_shaheer_2023/background.jpg",
    "background_image_original": "https://yts.mx/assets/images/movies/maharashtra_shaheer_2023/background.jpg",
    "small_cover_image": "https://yts.mx/assets/images/movies/maharashtra_shaheer_2023/small-cover.jpg",
    "medium_cover_image": "https://yts.mx/assets/images/movies/maharashtra_shaheer_2023/medium-cover.jpg",
    "large_cover_image": "https://yts.mx/assets/images/movies/maharashtra_shaheer_2023/large-cover.jpg",
    "state": "ok",
    "torrents": [
      {
        "url": "https://yts.mx/torrent/download/E4ABD3419B068316C000B312B397B6A087C5C2EA",
        "hash": "E4ABD3419B068316C000B312B397B6A087C5C2EA",
        "quality": "720p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 2,
        "peers": 1,
        "size": "1.33 GB",
        "size_bytes": 1428076626,
        "date_uploaded": "2023-06-16 14:49:51",
        "date_uploaded_unix": 1686919791
      },
      {
        "url": "https://yts.mx/torrent/download/51754FD8A8E5F94D6C061A3135DF1EE365542BC5",
        "hash": "51754FD8A8E5F94D6C061A3135DF1EE365542BC5",
        "quality": "1080p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "5.1",
        "seeds": 4,
        "peers": 1,
        "size": "2.72 GB",
        "size_bytes": 2920577761,
        "date_uploaded": "2023-06-16 16:31:05",
        "date_uploaded_unix": 1686925865
      }
    ],
    "date_uploaded": "2023-06-16 14:49:51",
    "date_uploaded_unix": 1686919791
  },
  {
    "id": 53277,
    "url": "https://yts.mx/movies/yuzuru-hanyu-ice-story-gift-at-tokyo-dome-2023",
    "imdb_code": "tt26919016",
    "title": "Yuzuru Hanyu Ice Story GIFT at Tokyo Dome",
    "title_english": "Yuzuru Hanyu Ice Story GIFT at Tokyo Dome",
    "title_long": "Yuzuru Hanyu Ice Story GIFT at Tokyo Dome (2023)",
    "slug": "yuzuru-hanyu-ice-story-gift-at-tokyo-dome-2023",
    "year": 2023,
    "rating": 9.1,
    "runtime": 162,
    "genres": [
      "Documentary",
      "Sport"
    ],
    "summary": "The first-ever solo ice show at Tokyo Dome, \"GIFT,\" is a story that self-portrays Yuzuru Hanyu's life and future on the ice.",
    "description_full": "The first-ever solo ice show at Tokyo Dome, \"GIFT,\" is a story that self-portrays Yuzuru Hanyu's life and future on the ice.",
    "synopsis": "The first-ever solo ice show at Tokyo Dome, \"GIFT,\" is a story that self-portrays Yuzuru Hanyu's life and future on the ice.",
    "yt_trailer_code": "inm7IGWOSqs",
    "language": "ja",
    "mpa_rating": "",
    "background_image": "https://yts.mx/assets/images/movies/yuzuru_hanyu_ice_story_gift_at_tokyo_dome_2023/background.jpg",
    "background_image_original": "https://yts.mx/assets/images/movies/yuzuru_hanyu_ice_story_gift_at_tokyo_dome_2023/background.jpg",
    "small_cover_image": "https://yts.mx/assets/images/movies/yuzuru_hanyu_ice_story_gift_at_tokyo_dome_2023/small-cover.jpg",
    "medium_cover_image": "https://yts.mx/assets/images/movies/yuzuru_hanyu_ice_story_gift_at_tokyo_dome_2023/medium-cover.jpg",
    "large_cover_image": "https://yts.mx/assets/images/movies/yuzuru_hanyu_ice_story_gift_at_tokyo_dome_2023/large-cover.jpg",
    "state": "ok",
    "torrents": [
      {
        "url": "https://yts.mx/torrent/download/88CFA33765971FB36F4F1DDA792E43FC716677A8",
        "hash": "88CFA33765971FB36F4F1DDA792E43FC716677A8",
        "quality": "720p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 7,
        "peers": 2,
        "size": "1.47 GB",
        "size_bytes": 1578400481,
        "date_uploaded": "2023-07-18 00:56:40",
        "date_uploaded_unix": 1689634600
      },
      {
        "url": "https://yts.mx/torrent/download/1F7BC5994851DD740EF0CD716D6CC6532C009B2E",
        "hash": "1F7BC5994851DD740EF0CD716D6CC6532C009B2E",
        "quality": "1080p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 10,
        "peers": 1,
        "size": "2.72 GB",
        "size_bytes": 2920577761,
        "date_uploaded": "2023-07-18 03:32:12",
        "date_uploaded_unix": 1689643932
      }
    ],
    "date_uploaded": "2023-07-18 00:56:40",
    "date_uploaded_unix": 1689634600
  },
  {
    "id": 47860,
    "url": "https://yts.mx/movies/ellegarden-lost-found-2022",
    "imdb_code": "tt24068168",
    "title": "ELLEGARDEN: Lost & Found",
    "title_english": "ELLEGARDEN: Lost & Found",
    "title_long": "ELLEGARDEN: Lost & Found (2022)",
    "slug": "ellegarden-lost-found-2022",
    "year": 2022,
    "rating": 8.7,
    "runtime": 0,
    "genres": [
      "Action",
      "Documentary"
    ],
    "summary": "A sensation to indies rock scene since 2000s and actively present today among fans even during their breaks. The first full-length documentary in the band's history starts from the production base in LA for the first album in 16 years, and navigates the stories from how they started, took break after breaking through, and reunited with nationwide fans awaited.",
    "description_full": "A sensation to indies rock scene since 2000s and actively present today among fans even during their breaks. The first full-length documentary in the band's history starts from the production base in LA for the first album in 16 years, and navigates the stories from how they started, took break after breaking through, and reunited with nationwide fans awaited.",
    "synopsis": "A sensation to indies rock scene since 2000s and actively present today among fans even during their breaks. The first full-length documentary in the band's history starts from the production base in LA for the first album in 16 years, and navigates the stories from how they started, took break after breaking through, and reunited with nationwide fans awaited.",
    "yt_trailer_code": "P96ipzWbyPQ",
    "language": "ja",
    "mpa_rating": "",
    "background_image": "https://yts.mx/assets/images/movies/ellegarden_lost_found_2022/background.jpg",
    "background_image_original": "https://yts.mx/assets/images/movies/ellegarden_lost_found_2022/background.jpg",
    "small_cover_image": "https://yts.mx/assets/images/movies/ellegarden_lost_found_2022/small-cover.jpg",
    "medium_cover_image": "https://yts.mx/assets/images/movies/ellegarden_lost_found_2022/medium-cover.jpg",
    "large_cover_image": "https://yts.mx/assets/images/movies/ellegarden_lost_found_2022/large-cover.jpg",
    "state": "ok",
    "torrents": [
      {
        "url": "https://yts.mx/torrent/download/D6EBC3E103D4320EF23A53BC241671F5FFC5E3CD",
        "hash": "D6EBC3E103D4320EF23A53BC241671F5FFC5E3CD",
        "quality": "720p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 1,
        "peers": 0,
        "size": "1.12 GB",
        "size_bytes": 1202590843,
        "date_uploaded": "2022-12-28 20:54:11",
        "date_uploaded_unix": 1672257251
      },
      {
        "url": "https://yts.mx/torrent/download/3769D5B432365C7B3878BD6BC2C2D2213BCE9348",
        "hash": "3769D5B432365C7B3878BD6BC2C2D2213BCE9348",
        "quality": "1080p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 4,
        "peers": 2,
        "size": "2.08 GB",
        "size_bytes": 2233382994,
        "date_uploaded": "2022-12-28 22:29:44",
        "date_uploaded_unix": 1672262984
      }
    ],
    "date_uploaded": "2022-12-28 20:54:11",
    "date_uploaded_unix": 1672257251
  },
  {
    "id": 42079,
    "url": "https://yts.mx/movies/the-kashmir-files-2022",
    "imdb_code": "tt10811166",
    "title": "The Kashmir Files",
    "title_english": "The Kashmir Files",
    "title_long": "The Kashmir Files (2022)",
    "slug": "the-kashmir-files-2022",
    "year": 2022,
    "rating": 8.7,
    "runtime": 170,
    "genres": [
      "Action",
      "Drama"
    ],
    "summary": "The story revolves around Krishna Pandit (Darshan Kumar), a JNU student, who thinks his parents were killed in an accident as told by his grandfather, Pushkar Nath (Anupam Kher). But the truth is more depressing. He is caught in the middle of two opposing narratives of the Kashmiri Pandit exodus of 1990. One side is represented by the pro-Azaadi JNU professor (Pallavi Joshi) who is gaining a lot of support on the campus for her Kashmir cause. On the other side is Nath, who has been struggling for 30 years to get justice for the exodus, which the professor claims is a sham. After Pushkar Naths death, Krishna goes back to Kashmir to fulfil his last wishes and also meets four of Naths friends, a journalist, a doctor, a former police officer, and a retired civil servant. They are shocked to know that Krishna didnt know the true story of his fathers death. The Kashmir Files then becomes a journey of discovering the truth for Krishna. In one among many traumatic scenes, Krishnas father, hiding in a container of rice, is killed by a local militant. His mother is forced to eat the blood-soaked rice from the same container.—apricci-34342",
    "description_full": "The story revolves around Krishna Pandit (Darshan Kumar), a JNU student, who thinks his parents were killed in an accident as told by his grandfather, Pushkar Nath (Anupam Kher). But the truth is more depressing. He is caught in the middle of two opposing narratives of the Kashmiri Pandit exodus of 1990. One side is represented by the pro-Azaadi JNU professor (Pallavi Joshi) who is gaining a lot of support on the campus for her Kashmir cause. On the other side is Nath, who has been struggling for 30 years to get justice for the exodus, which the professor claims is a sham. After Pushkar Naths death, Krishna goes back to Kashmir to fulfil his last wishes and also meets four of Naths friends, a journalist, a doctor, a former police officer, and a retired civil servant. They are shocked to know that Krishna didnt know the true story of his fathers death. The Kashmir Files then becomes a journey of discovering the truth for Krishna. In one among many traumatic scenes, Krishnas father, hiding in a container of rice, is killed by a local militant. His mother is forced to eat the blood-soaked rice from the same container.—apricci-34342",
    "synopsis": "The story revolves around Krishna Pandit (Darshan Kumar), a JNU student, who thinks his parents were killed in an accident as told by his grandfather, Pushkar Nath (Anupam Kher). But the truth is more depressing. He is caught in the middle of two opposing narratives of the Kashmiri Pandit exodus of 1990. One side is represented by the pro-Azaadi JNU professor (Pallavi Joshi) who is gaining a lot of support on the campus for her Kashmir cause. On the other side is Nath, who has been struggling for 30 years to get justice for the exodus, which the professor claims is a sham. After Pushkar Naths death, Krishna goes back to Kashmir to fulfil his last wishes and also meets four of Naths friends, a journalist, a doctor, a former police officer, and a retired civil servant. They are shocked to know that Krishna didnt know the true story of his fathers death. The Kashmir Files then becomes a journey of discovering the truth for Krishna. In one among many traumatic scenes, Krishnas father, hiding in a container of rice, is killed by a local militant. His mother is forced to eat the blood-soaked rice from the same container.—apricci-34342",
    "yt_trailer_code": "",
    "language": "hi",
    "mpa_rating": "",
    "background_image": "https://yts.mx/assets/images/movies/the_kashmir_files_2022/background.jpg",
    "background_image_original": "https://yts.mx/assets/images/movies/the_kashmir_files_2022/background.jpg",
    "small_cover_image": "https://yts.mx/assets/images/movies/the_kashmir_files_2022/small-cover.jpg",
    "medium_cover_image": "https://yts.mx/assets/images/movies/the_kashmir_files_2022/medium-cover.jpg",
    "large_cover_image": "https://yts.mx/assets/images/movies/the_kashmir_files_2022/large-cover.jpg",
    "state": "ok",
    "torrents": [
      {
        "url": "https://yts.mx/torrent/download/F158924FAF579F76A60CA357FC8EB7C4D94DFFA8",
        "hash": "F158924FAF579F76A60CA357FC8EB7C4D94DFFA8",
        "quality": "720p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 24,
        "peers": 3,
        "size": "1.47 GB",
        "size_bytes": 1578400481,
        "date_uploaded": "2022-05-14 21:34:38",
        "date_uploaded_unix": 1652556878
      },
      {
        "url": "https://yts.mx/torrent/download/2496423EEC3146AE9A9BFC62AE1FFB8571D3370C",
        "hash": "2496423EEC3146AE9A9BFC62AE1FFB8571D3370C",
        "quality": "1080p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "5.1",
        "seeds": 41,
        "peers": 4,
        "size": "3.02 GB",
        "size_bytes": 3242700308,
        "date_uploaded": "2022-05-14 23:06:23",
        "date_uploaded_unix": 1652562383
      }
    ],
    "date_uploaded": "2022-05-14 21:34:38",
    "date_uploaded_unix": 1652556878
  },
  {
    "id": 49398,
    "url": "https://yts.mx/movies/son-of-a-mother-2022",
    "imdb_code": "tt21339834",
    "title": "Son of a Mother",
    "title_english": "Son of a Mother",
    "title_long": "Son of a Mother (2022)",
    "slug": "son-of-a-mother-2022",
    "year": 2022,
    "rating": 8.5,
    "runtime": 111,
    "genres": [
      "Biography",
      "Comedy",
      "Documentary"
    ],
    "summary": "É para quem está com saudade de gargalhar com Paulo Gustavo. O documentário 'FILHO DA MÃE' acompanha os bastidores da última turnê do ator: um show musical com a mãe, Dona Déa, sua grande inspiração para criar Dona Hermínia - personagem principal de \"Minha mãe é uma peça\", o maior sucesso da história do cinema brasileiro. Com imagens inéditas, o filme mostra a intimidade deliciosa entre os dois e ainda traz fotos e vídeos da infância e adolescência do ator. Para completar, amigos próximos contam como era conviver com o Paulo. Prepare-se para rir, chorar e lembrar por que Paulo Gustavo é e sempre será inesquecível.",
    "description_full": "É para quem está com saudade de gargalhar com Paulo Gustavo. O documentário 'FILHO DA MÃE' acompanha os bastidores da última turnê do ator: um show musical com a mãe, Dona Déa, sua grande inspiração para criar Dona Hermínia - personagem principal de \"Minha mãe é uma peça\", o maior sucesso da história do cinema brasileiro. Com imagens inéditas, o filme mostra a intimidade deliciosa entre os dois e ainda traz fotos e vídeos da infância e adolescência do ator. Para completar, amigos próximos contam como era conviver com o Paulo. Prepare-se para rir, chorar e lembrar por que Paulo Gustavo é e sempre será inesquecível.",
    "synopsis": "É para quem está com saudade de gargalhar com Paulo Gustavo. O documentário 'FILHO DA MÃE' acompanha os bastidores da última turnê do ator: um show musical com a mãe, Dona Déa, sua grande inspiração para criar Dona Hermínia - personagem principal de \"Minha mãe é uma peça\", o maior sucesso da história do cinema brasileiro. Com imagens inéditas, o filme mostra a intimidade deliciosa entre os dois e ainda traz fotos e vídeos da infância e adolescência do ator. Para completar, amigos próximos contam como era conviver com o Paulo. Prepare-se para rir, chorar e lembrar por que Paulo Gustavo é e sempre será inesquecível.",
    "yt_trailer_code": "",
    "language": "pt",
    "mpa_rating": "",
    "background_image": "https://yts.mx/assets/images/movies/filho_da_mae_2022/background.jpg",
    "background_image_original": "https://yts.mx/assets/images/movies/filho_da_mae_2022/background.jpg",
    "small_cover_image": "https://yts.mx/assets/images/movies/filho_da_mae_2022/small-cover.jpg",
    "medium_cover_image": "https://yts.mx/assets/images/movies/filho_da_mae_2022/medium-cover.jpg",
    "large_cover_image": "https://yts.mx/assets/images/movies/filho_da_mae_2022/large-cover.jpg",
    "state": "ok",
    "torrents": [
      {
        "url": "https://yts.mx/torrent/download/BA8D6BF84622C887B0D2410828BD0EF25278010A",
        "hash": "BA8D6BF84622C887B0D2410828BD0EF25278010A",
        "quality": "720p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 0,
        "peers": 0,
        "size": "1 GB",
        "size_bytes": 1073741824,
        "date_uploaded": "2023-03-03 06:08:36",
        "date_uploaded_unix": 1677820116
      },
      {
        "url": "https://yts.mx/torrent/download/FBED3A693484ED898CBBFBA30AFF67B51B45154F",
        "hash": "FBED3A693484ED898CBBFBA30AFF67B51B45154F",
        "quality": "1080p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "5.1",
        "seeds": 1,
        "peers": 1,
        "size": "2.06 GB",
        "size_bytes": 2211908157,
        "date_uploaded": "2023-03-03 07:20:33",
        "date_uploaded_unix": 1677824433
      }
    ],
    "date_uploaded": "2023-03-03 06:08:36",
    "date_uploaded_unix": 1677820116
  },
  {
    "id": 48341,
    "url": "https://yts.mx/movies/puscifer-parole-violator-2022",
    "imdb_code": "tt26244184",
    "title": "Puscifer: Parole Violator",
    "title_english": "Puscifer: Parole Violator",
    "title_long": "Puscifer: Parole Violator (2022)",
    "slug": "puscifer-parole-violator-2022",
    "year": 2022,
    "rating": 8.9,
    "runtime": 0,
    "genres": [
      "Action",
      "Documentary",
      "Music"
    ],
    "summary": "This is a live soundtrack to the recent Puscifer Pay Per View, filmed and recorded at the Wiltern Theatre in Los Angeles. It features new live recordings of the classic album \"Conditions of my Parole\".",
    "description_full": "This is a live soundtrack to the recent Puscifer Pay Per View, filmed and recorded at the Wiltern Theatre in Los Angeles. It features new live recordings of the classic album \"Conditions of my Parole\".",
    "synopsis": "This is a live soundtrack to the recent Puscifer Pay Per View, filmed and recorded at the Wiltern Theatre in Los Angeles. It features new live recordings of the classic album \"Conditions of my Parole\".",
    "yt_trailer_code": "",
    "language": "en",
    "mpa_rating": "",
    "background_image": "https://yts.mx/assets/images/movies/puscifer_parole_violator_2022/background.jpg",
    "background_image_original": "https://yts.mx/assets/images/movies/puscifer_parole_violator_2022/background.jpg",
    "small_cover_image": "https://yts.mx/assets/images/movies/puscifer_parole_violator_2022/small-cover.jpg",
    "medium_cover_image": "https://yts.mx/assets/images/movies/puscifer_parole_violator_2022/medium-cover.jpg",
    "large_cover_image": "https://yts.mx/assets/images/movies/puscifer_parole_violator_2022/large-cover.jpg",
    "state": "ok",
    "torrents": [
      {
        "url": "https://yts.mx/torrent/download/F770F7B31BAAE1D9AB04037BC9F5DB6207CD114C",
        "hash": "F770F7B31BAAE1D9AB04037BC9F5DB6207CD114C",
        "quality": "720p",
        "type": "bluray",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 1,
        "peers": 0,
        "size": "597.03 MB",
        "size_bytes": 626031329,
        "date_uploaded": "2023-01-19 23:01:16",
        "date_uploaded_unix": 1674165676
      },
      {
        "url": "https://yts.mx/torrent/download/C39AB89F1EEA38E5332D4F1174F9FE5F667AB97C",
        "hash": "C39AB89F1EEA38E5332D4F1174F9FE5F667AB97C",
        "quality": "1080p",
        "type": "bluray",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 13,
        "peers": 0,
        "size": "1.08 GB",
        "size_bytes": 1159641170,
        "date_uploaded": "2023-01-19 23:41:27",
        "date_uploaded_unix": 1674168087
      }
    ],
    "date_uploaded": "2023-01-19 23:01:16",
    "date_uploaded_unix": 1674165676
  },
  {
    "id": 44943,
    "url": "https://yts.mx/movies/taylor-hawkins-tribute-concert-2022",
    "imdb_code": "tt21984858",
    "title": "Taylor Hawkins Tribute Concert",
    "title_english": "Taylor Hawkins Tribute Concert",
    "title_long": "Taylor Hawkins Tribute Concert (2022)",
    "slug": "taylor-hawkins-tribute-concert-2022",
    "year": 2022,
    "rating": 8.8,
    "runtime": 339,
    "genres": [
      "Action",
      "Music"
    ],
    "summary": "An all-star global music event live from London's Taylor Hawkins Tribute Concert featuring the biggest names in music joining together in celebration of the life, music and love of Taylor Hawkins, modern music's most beloved figures.",
    "description_full": "An all-star global music event live from London's Taylor Hawkins Tribute Concert featuring the biggest names in music joining together in celebration of the life, music and love of Taylor Hawkins, modern music's most beloved figures.",
    "synopsis": "An all-star global music event live from London's Taylor Hawkins Tribute Concert featuring the biggest names in music joining together in celebration of the life, music and love of Taylor Hawkins, modern music's most beloved figures.",
    "yt_trailer_code": "tptBRUTxRXc",
    "language": "en",
    "mpa_rating": "",
    "background_image": "https://yts.mx/assets/images/movies/taylor_hawkins_tribute_concert_2022/background.jpg",
    "background_image_original": "https://yts.mx/assets/images/movies/taylor_hawkins_tribute_concert_2022/background.jpg",
    "small_cover_image": "https://yts.mx/assets/images/movies/taylor_hawkins_tribute_concert_2022/small-cover.jpg",
    "medium_cover_image": "https://yts.mx/assets/images/movies/taylor_hawkins_tribute_concert_2022/medium-cover.jpg",
    "large_cover_image": "https://yts.mx/assets/images/movies/taylor_hawkins_tribute_concert_2022/large-cover.jpg",
    "state": "ok",
    "torrents": [
      {
        "url": "https://yts.mx/torrent/download/A8B0DDC0DAA2B6367FDB6317AEA8C7C6952653E5",
        "hash": "A8B0DDC0DAA2B6367FDB6317AEA8C7C6952653E5",
        "quality": "720p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 5,
        "peers": 1,
        "size": "3.05 GB",
        "size_bytes": 3274912563,
        "date_uploaded": "2022-09-08 02:22:23",
        "date_uploaded_unix": 1662596543
      },
      {
        "url": "https://yts.mx/torrent/download/6E33119C84F7634CCA354F7D7D4A90CCC08CB572",
        "hash": "6E33119C84F7634CCA354F7D7D4A90CCC08CB572",
        "quality": "1080p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 11,
        "peers": 2,
        "size": "5.66 GB",
        "size_bytes": 6077378724,
        "date_uploaded": "2022-09-08 07:08:21",
        "date_uploaded_unix": 1662613701
      }
    ],
    "date_uploaded": "2022-09-08 02:22:23",
    "date_uploaded_unix": 1662596543
  },
  {
    "id": 43856,
    "url": "https://yts.mx/movies/rocketry-the-nambi-effect-2022",
    "imdb_code": "tt9263550",
    "title": "Rocketry: The Nambi Effect",
    "title_english": "Rocketry: The Nambi Effect",
    "title_long": "Rocketry: The Nambi Effect (2022)",
    "slug": "rocketry-the-nambi-effect-2022",
    "year": 2022,
    "rating": 8.7,
    "runtime": 157,
    "genres": [
      "Action",
      "Biography",
      "Drama",
      "Sci-Fi"
    ],
    "summary": "During the present time in a televised interview with actor Shah Rukh Khan (Hindi)/Suriya (Tamil), Nambi walks through the events leading to his rise as an eminent engineer to alleged espionage charges, and physical and mental cruelty against him.Nambi starts with his experiences at the Thumba Equatorial Rocket Launching Station, where he saves A. P. J. Abdul Kalam, one of his team members from a major injury during an experiment. In 1969, he is accepted into Princeton University in the US.Nambi successfully completes his MSE program in chemical rocket propulsion under professor Luigi Crocco who recommends him for the NASA fellowship. However, after a brief stint at NASA with Barry Amaldev, he is offered a generous paycheck and other allowances. He rejects it and returns to India so that he may make use of his talents at ISRO. Subsequently, he also manages to get 400 million pounds of equipment from Scotland for free. However, after the suspicious death of Vikram Sarabhai, he did not have adequate support from ISRO or funds from the Indian government to continue his research.At this point, Nambi strikes a deal with the French who need skilled scientists to help them build their own liquid fuel engine. He then moves to France with his colleagues, hoping to learn from France's advanced technology so that they may recreate it back in India. Unbeknownst to the French, Nambi and his 52 colleagues have learnt French before their journey but pretend to not understand them. After being kept out of their major discussions, Nambi's team tries to find a way to gain access to these meetings and test data. It is then that they discover that the French engine is faulty. Nambi uses this opportunity to gain access to the required data in exchange for fixing the engine. The team then returns to India and start working on building their own engine on liquid fuels. However, due to a lack of resources, it takes 8 more years to complete. They test the engine at the same testing facility in France - it goes above the 135-pressure mark and goes all the way to 180. Successful in his plans, Nambi returns to India after naming the engine VIKAS after Vikram Sarabhai, his mentor.Nambi's focus is now on cryogenic engines which he believes will make India competent to participate in the world satellite market. Knowing ISRO's limitations in terms of time and resources, Nambi decides to purchase these engines from some other country. He strikes a deal with Russia (then USSR) after informing them that he knows about their cryogenic missiles, told to him by his Russian friend in Princeton. He requests 4 of them to be imported to India. After the Russians agree, the Americans find out about this deal and try their best to break it. While USSR is on the brink of collapse, Nambi and his colleagues manage to expedite the transfer process and sneak out a couple of engines from under the Americans' noses with the help of the Russians.Back in India, Nambi is arrested out of the blue while news of his treason spreads like wildfire. He is taken to a guest house in Trivandrum where he is beaten and tortured in an attempt to make him confess to his alleged crimes. He also recognizes that the officials are trying to make him repeat their sentences and that there is a recording device in the room to capture it. However, Nambi holds his ground and denies all charges. It was alleged that Nambi met Mariam, a Maldivian woman, in a hotel in Chennai and after being caught in her trap, he was forced to sell India's rocketry secrets to Pakistan. After being hospitalized due to his injuries, Nambi is met by CBI official P. M. Nair, who thoroughly investigates the matter. Nair brings Mariam and her friend, along with a few others into the room. Mariam and her friend reveal that the Kerala police officer in charge of the investigation, Gopal, tortured and threatened them and made them falsely incriminate Nambi, whom they have never met before. They also apologize to Nambi for ruining his reputation and causing pain to him and his family. Nair also figures out that all the accused in this case were members of ISRO's cryogenic wing, and concludes that it was a huge ploy by some powerful parties to hinder India's progress in the cryogenic sector.Months later, Nambi receives bail and returns to his house to find his family members traumatized by the way they were treated by others. Nambi's wife Meena is in need of psychiatric help and the rest of his family are still shunned by society. Hence, Nambi decides that he has to clear his name so that his family may lead normal lives in the future. Years later, Nambi is proven innocent by the Supreme Court and returns to ISRO, helping his colleagues with the Mangalyaan mission. Nambi is later awarded the Padma Bhushan for his contributions to Indian Space Research.After hearing his story, Shah Rukh Khan (Hindi)/Suriya (Tamil) feels so bad for Nambi, that he apologizes to Nambi on the behalf of the whole nation, as the interview ends. The real Nambi is shown receiving the Padma Bhushan award from the president, Ram Nath Kovind.",
    "description_full": "During the present time in a televised interview with actor Shah Rukh Khan (Hindi)/Suriya (Tamil), Nambi walks through the events leading to his rise as an eminent engineer to alleged espionage charges, and physical and mental cruelty against him.Nambi starts with his experiences at the Thumba Equatorial Rocket Launching Station, where he saves A. P. J. Abdul Kalam, one of his team members from a major injury during an experiment. In 1969, he is accepted into Princeton University in the US.Nambi successfully completes his MSE program in chemical rocket propulsion under professor Luigi Crocco who recommends him for the NASA fellowship. However, after a brief stint at NASA with Barry Amaldev, he is offered a generous paycheck and other allowances. He rejects it and returns to India so that he may make use of his talents at ISRO. Subsequently, he also manages to get 400 million pounds of equipment from Scotland for free. However, after the suspicious death of Vikram Sarabhai, he did not have adequate support from ISRO or funds from the Indian government to continue his research.At this point, Nambi strikes a deal with the French who need skilled scientists to help them build their own liquid fuel engine. He then moves to France with his colleagues, hoping to learn from France's advanced technology so that they may recreate it back in India. Unbeknownst to the French, Nambi and his 52 colleagues have learnt French before their journey but pretend to not understand them. After being kept out of their major discussions, Nambi's team tries to find a way to gain access to these meetings and test data. It is then that they discover that the French engine is faulty. Nambi uses this opportunity to gain access to the required data in exchange for fixing the engine. The team then returns to India and start working on building their own engine on liquid fuels. However, due to a lack of resources, it takes 8 more years to complete. They test the engine at the same testing facility in France - it goes above the 135-pressure mark and goes all the way to 180. Successful in his plans, Nambi returns to India after naming the engine VIKAS after Vikram Sarabhai, his mentor.Nambi's focus is now on cryogenic engines which he believes will make India competent to participate in the world satellite market. Knowing ISRO's limitations in terms of time and resources, Nambi decides to purchase these engines from some other country. He strikes a deal with Russia (then USSR) after informing them that he knows about their cryogenic missiles, told to him by his Russian friend in Princeton. He requests 4 of them to be imported to India. After the Russians agree, the Americans find out about this deal and try their best to break it. While USSR is on the brink of collapse, Nambi and his colleagues manage to expedite the transfer process and sneak out a couple of engines from under the Americans' noses with the help of the Russians.Back in India, Nambi is arrested out of the blue while news of his treason spreads like wildfire. He is taken to a guest house in Trivandrum where he is beaten and tortured in an attempt to make him confess to his alleged crimes. He also recognizes that the officials are trying to make him repeat their sentences and that there is a recording device in the room to capture it. However, Nambi holds his ground and denies all charges. It was alleged that Nambi met Mariam, a Maldivian woman, in a hotel in Chennai and after being caught in her trap, he was forced to sell India's rocketry secrets to Pakistan. After being hospitalized due to his injuries, Nambi is met by CBI official P. M. Nair, who thoroughly investigates the matter. Nair brings Mariam and her friend, along with a few others into the room. Mariam and her friend reveal that the Kerala police officer in charge of the investigation, Gopal, tortured and threatened them and made them falsely incriminate Nambi, whom they have never met before. They also apologize to Nambi for ruining his reputation and causing pain to him and his family. Nair also figures out that all the accused in this case were members of ISRO's cryogenic wing, and concludes that it was a huge ploy by some powerful parties to hinder India's progress in the cryogenic sector.Months later, Nambi receives bail and returns to his house to find his family members traumatized by the way they were treated by others. Nambi's wife Meena is in need of psychiatric help and the rest of his family are still shunned by society. Hence, Nambi decides that he has to clear his name so that his family may lead normal lives in the future. Years later, Nambi is proven innocent by the Supreme Court and returns to ISRO, helping his colleagues with the Mangalyaan mission. Nambi is later awarded the Padma Bhushan for his contributions to Indian Space Research.After hearing his story, Shah Rukh Khan (Hindi)/Suriya (Tamil) feels so bad for Nambi, that he apologizes to Nambi on the behalf of the whole nation, as the interview ends. The real Nambi is shown receiving the Padma Bhushan award from the president, Ram Nath Kovind.",
    "synopsis": "During the present time in a televised interview with actor Shah Rukh Khan (Hindi)/Suriya (Tamil), Nambi walks through the events leading to his rise as an eminent engineer to alleged espionage charges, and physical and mental cruelty against him.Nambi starts with his experiences at the Thumba Equatorial Rocket Launching Station, where he saves A. P. J. Abdul Kalam, one of his team members from a major injury during an experiment. In 1969, he is accepted into Princeton University in the US.Nambi successfully completes his MSE program in chemical rocket propulsion under professor Luigi Crocco who recommends him for the NASA fellowship. However, after a brief stint at NASA with Barry Amaldev, he is offered a generous paycheck and other allowances. He rejects it and returns to India so that he may make use of his talents at ISRO. Subsequently, he also manages to get 400 million pounds of equipment from Scotland for free. However, after the suspicious death of Vikram Sarabhai, he did not have adequate support from ISRO or funds from the Indian government to continue his research.At this point, Nambi strikes a deal with the French who need skilled scientists to help them build their own liquid fuel engine. He then moves to France with his colleagues, hoping to learn from France's advanced technology so that they may recreate it back in India. Unbeknownst to the French, Nambi and his 52 colleagues have learnt French before their journey but pretend to not understand them. After being kept out of their major discussions, Nambi's team tries to find a way to gain access to these meetings and test data. It is then that they discover that the French engine is faulty. Nambi uses this opportunity to gain access to the required data in exchange for fixing the engine. The team then returns to India and start working on building their own engine on liquid fuels. However, due to a lack of resources, it takes 8 more years to complete. They test the engine at the same testing facility in France - it goes above the 135-pressure mark and goes all the way to 180. Successful in his plans, Nambi returns to India after naming the engine VIKAS after Vikram Sarabhai, his mentor.Nambi's focus is now on cryogenic engines which he believes will make India competent to participate in the world satellite market. Knowing ISRO's limitations in terms of time and resources, Nambi decides to purchase these engines from some other country. He strikes a deal with Russia (then USSR) after informing them that he knows about their cryogenic missiles, told to him by his Russian friend in Princeton. He requests 4 of them to be imported to India. After the Russians agree, the Americans find out about this deal and try their best to break it. While USSR is on the brink of collapse, Nambi and his colleagues manage to expedite the transfer process and sneak out a couple of engines from under the Americans' noses with the help of the Russians.Back in India, Nambi is arrested out of the blue while news of his treason spreads like wildfire. He is taken to a guest house in Trivandrum where he is beaten and tortured in an attempt to make him confess to his alleged crimes. He also recognizes that the officials are trying to make him repeat their sentences and that there is a recording device in the room to capture it. However, Nambi holds his ground and denies all charges. It was alleged that Nambi met Mariam, a Maldivian woman, in a hotel in Chennai and after being caught in her trap, he was forced to sell India's rocketry secrets to Pakistan. After being hospitalized due to his injuries, Nambi is met by CBI official P. M. Nair, who thoroughly investigates the matter. Nair brings Mariam and her friend, along with a few others into the room. Mariam and her friend reveal that the Kerala police officer in charge of the investigation, Gopal, tortured and threatened them and made them falsely incriminate Nambi, whom they have never met before. They also apologize to Nambi for ruining his reputation and causing pain to him and his family. Nair also figures out that all the accused in this case were members of ISRO's cryogenic wing, and concludes that it was a huge ploy by some powerful parties to hinder India's progress in the cryogenic sector.Months later, Nambi receives bail and returns to his house to find his family members traumatized by the way they were treated by others. Nambi's wife Meena is in need of psychiatric help and the rest of his family are still shunned by society. Hence, Nambi decides that he has to clear his name so that his family may lead normal lives in the future. Years later, Nambi is proven innocent by the Supreme Court and returns to ISRO, helping his colleagues with the Mangalyaan mission. Nambi is later awarded the Padma Bhushan for his contributions to Indian Space Research.After hearing his story, Shah Rukh Khan (Hindi)/Suriya (Tamil) feels so bad for Nambi, that he apologizes to Nambi on the behalf of the whole nation, as the interview ends. The real Nambi is shown receiving the Padma Bhushan award from the president, Ram Nath Kovind.",
    "yt_trailer_code": "E3s-w-G4R_w",
    "language": "ta",
    "mpa_rating": "",
    "background_image": "https://yts.mx/assets/images/movies/rocketry_the_nambi_effect_2022/background.jpg",
    "background_image_original": "https://yts.mx/assets/images/movies/rocketry_the_nambi_effect_2022/background.jpg",
    "small_cover_image": "https://yts.mx/assets/images/movies/rocketry_the_nambi_effect_2022/small-cover.jpg",
    "medium_cover_image": "https://yts.mx/assets/images/movies/rocketry_the_nambi_effect_2022/medium-cover.jpg",
    "large_cover_image": "https://yts.mx/assets/images/movies/rocketry_the_nambi_effect_2022/large-cover.jpg",
    "state": "ok",
    "torrents": [
      {
        "url": "https://yts.mx/torrent/download/4E24F996F258031F4FF0AD8D4ED4EB2E39EF72A7",
        "hash": "4E24F996F258031F4FF0AD8D4ED4EB2E39EF72A7",
        "quality": "720p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 23,
        "peers": 2,
        "size": "1.34 GB",
        "size_bytes": 1438814044,
        "date_uploaded": "2022-07-29 13:51:11",
        "date_uploaded_unix": 1659095471
      },
      {
        "url": "https://yts.mx/torrent/download/C6616B7143513910CD6642133111F9204A759F6F",
        "hash": "C6616B7143513910CD6642133111F9204A759F6F",
        "quality": "1080p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "5.1",
        "seeds": 26,
        "peers": 2,
        "size": "2.76 GB",
        "size_bytes": 2963527434,
        "date_uploaded": "2022-07-29 15:19:36",
        "date_uploaded_unix": 1659100776
      }
    ],
    "date_uploaded": "2022-07-29 13:51:11",
    "date_uploaded_unix": 1659095471
  },
  {
    "id": 52102,
    "url": "https://yts.mx/movies/afghan-dreamers-2022",
    "imdb_code": "tt21247214",
    "title": "Afghan Dreamers",
    "title_english": "Afghan Dreamers",
    "title_long": "Afghan Dreamers (2022)",
    "slug": "afghan-dreamers-2022",
    "year": 2022,
    "rating": 8.7,
    "runtime": 72,
    "genres": [
      "Documentary"
    ],
    "summary": "An all-girls' robotics team in Afghanistan risks it all to prove that it can compete against anyone in the world, and demonstrates that girls can become scientists and engineers instead of teenage brides. Working in secret under Taliban rule, the high-school-aged team members struggle in the face of immense odds and ever present danger, and single-handedly begin to change perceptions in this entrenched Islamic culture. The film focuses on three team members - Fatemah, Somaya, and Lida - all of whom are fiercely determined to follow their passions and become role models for the next generation. Afghan Dreamers is a film that dares to ask if a better future is possible for women in a country like theirs.—DG",
    "description_full": "An all-girls' robotics team in Afghanistan risks it all to prove that it can compete against anyone in the world, and demonstrates that girls can become scientists and engineers instead of teenage brides. Working in secret under Taliban rule, the high-school-aged team members struggle in the face of immense odds and ever present danger, and single-handedly begin to change perceptions in this entrenched Islamic culture. The film focuses on three team members - Fatemah, Somaya, and Lida - all of whom are fiercely determined to follow their passions and become role models for the next generation. Afghan Dreamers is a film that dares to ask if a better future is possible for women in a country like theirs.—DG",
    "synopsis": "An all-girls' robotics team in Afghanistan risks it all to prove that it can compete against anyone in the world, and demonstrates that girls can become scientists and engineers instead of teenage brides. Working in secret under Taliban rule, the high-school-aged team members struggle in the face of immense odds and ever present danger, and single-handedly begin to change perceptions in this entrenched Islamic culture. The film focuses on three team members - Fatemah, Somaya, and Lida - all of whom are fiercely determined to follow their passions and become role models for the next generation. Afghan Dreamers is a film that dares to ask if a better future is possible for women in a country like theirs.—DG",
    "yt_trailer_code": "ZWYIIHObnLc",
    "language": "ab",
    "mpa_rating": "",
    "background_image": "https://yts.mx/assets/images/movies/afghan_dreamers_2022/background.jpg",
    "background_image_original": "https://yts.mx/assets/images/movies/afghan_dreamers_2022/background.jpg",
    "small_cover_image": "https://yts.mx/assets/images/movies/afghan_dreamers_2022/small-cover.jpg",
    "medium_cover_image": "https://yts.mx/assets/images/movies/afghan_dreamers_2022/medium-cover.jpg",
    "large_cover_image": "https://yts.mx/assets/images/movies/afghan_dreamers_2022/large-cover.jpg",
    "state": "ok",
    "torrents": [
      {
        "url": "https://yts.mx/torrent/download/97DFAA2AFFD0AD74709A42D3E8B26825CB07D34D",
        "hash": "97DFAA2AFFD0AD74709A42D3E8B26825CB07D34D",
        "quality": "720p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 3,
        "peers": 2,
        "size": "662.07 MB",
        "size_bytes": 694230712,
        "date_uploaded": "2023-05-23 08:50:25",
        "date_uploaded_unix": 1684824625
      },
      {
        "url": "https://yts.mx/torrent/download/285F0C32BEA0E1BD8A54A09D68DB25BA3EB0E49E",
        "hash": "285F0C32BEA0E1BD8A54A09D68DB25BA3EB0E49E",
        "quality": "1080p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "5.1",
        "seeds": 1,
        "peers": 0,
        "size": "1.33 GB",
        "size_bytes": 1428076626,
        "date_uploaded": "2023-05-23 09:48:15",
        "date_uploaded_unix": 1684828095
      }
    ],
    "date_uploaded": "2023-05-23 08:50:25",
    "date_uploaded_unix": 1684824625
  },
  {
    "id": 52164,
    "url": "https://yts.mx/movies/the-art-of-un-war-2022",
    "imdb_code": "tt20101780",
    "title": "The Art of Un-War",
    "title_english": "The Art of Un-War",
    "title_long": "The Art of Un-War (2022)",
    "slug": "the-art-of-un-war-2022",
    "year": 2022,
    "rating": 9.3,
    "runtime": 64,
    "genres": [
      "Documentary"
    ],
    "summary": "The Art of Un-War is an in-depth exploration of renowned artist Krzysztof Wodiczko's life and the art interventions he creates as powerful responses to the inequities and horrors of war and injustice. Throughout the film, the artist's powerful interventions become examples of how art can be used to disrupt public complacency. The evolution of Wodiczko's political art unfolds throughout the film from his first intervention created in Warsaw in 1968, to one of his most ambitious projects and a focal point of the film - a radical proposal to transform Paris' Arc De Triomphe war monument into a site for peace-building research and activism. Wodiczko counters the monument's glorification of war and portrayal of distorted histories by constructing scaffolding around the Arc De Triomphe and transforming it into its complete antithesis.—Maria Niro",
    "description_full": "The Art of Un-War is an in-depth exploration of renowned artist Krzysztof Wodiczko's life and the art interventions he creates as powerful responses to the inequities and horrors of war and injustice. Throughout the film, the artist's powerful interventions become examples of how art can be used to disrupt public complacency. The evolution of Wodiczko's political art unfolds throughout the film from his first intervention created in Warsaw in 1968, to one of his most ambitious projects and a focal point of the film - a radical proposal to transform Paris' Arc De Triomphe war monument into a site for peace-building research and activism. Wodiczko counters the monument's glorification of war and portrayal of distorted histories by constructing scaffolding around the Arc De Triomphe and transforming it into its complete antithesis.—Maria Niro",
    "synopsis": "The Art of Un-War is an in-depth exploration of renowned artist Krzysztof Wodiczko's life and the art interventions he creates as powerful responses to the inequities and horrors of war and injustice. Throughout the film, the artist's powerful interventions become examples of how art can be used to disrupt public complacency. The evolution of Wodiczko's political art unfolds throughout the film from his first intervention created in Warsaw in 1968, to one of his most ambitious projects and a focal point of the film - a radical proposal to transform Paris' Arc De Triomphe war monument into a site for peace-building research and activism. Wodiczko counters the monument's glorification of war and portrayal of distorted histories by constructing scaffolding around the Arc De Triomphe and transforming it into its complete antithesis.—Maria Niro",
    "yt_trailer_code": "O25cnBmvXA0",
    "language": "en",
    "mpa_rating": "",
    "background_image": "https://yts.mx/assets/images/movies/the_art_of_un_war_2022/background.jpg",
    "background_image_original": "https://yts.mx/assets/images/movies/the_art_of_un_war_2022/background.jpg",
    "small_cover_image": "https://yts.mx/assets/images/movies/the_art_of_un_war_2022/small-cover.jpg",
    "medium_cover_image": "https://yts.mx/assets/images/movies/the_art_of_un_war_2022/medium-cover.jpg",
    "large_cover_image": "https://yts.mx/assets/images/movies/the_art_of_un_war_2022/large-cover.jpg",
    "state": "ok",
    "torrents": [
      {
        "url": "https://yts.mx/torrent/download/FA74F8114183331EC9C9BE98A632C4C2A619ABFE",
        "hash": "FA74F8114183331EC9C9BE98A632C4C2A619ABFE",
        "quality": "720p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 5,
        "peers": 2,
        "size": "575.04 MB",
        "size_bytes": 602973143,
        "date_uploaded": "2023-05-24 03:54:59",
        "date_uploaded_unix": 1684893299
      },
      {
        "url": "https://yts.mx/torrent/download/DAF94C354428A2528D4684E3A11229D46589B081",
        "hash": "DAF94C354428A2528D4684E3A11229D46589B081",
        "quality": "1080p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 10,
        "peers": 6,
        "size": "1.04 GB",
        "size_bytes": 1116691497,
        "date_uploaded": "2023-05-24 04:43:44",
        "date_uploaded_unix": 1684896224
      }
    ],
    "date_uploaded": "2023-05-24 03:54:59",
    "date_uploaded_unix": 1684893299
  },
  {
    "id": 46035,
    "url": "https://yts.mx/movies/the-big-steppers-tour-live-from-paris-2022",
    "imdb_code": "tt22940628",
    "title": "The Big Steppers Tour: Live from Paris",
    "title_english": "The Big Steppers Tour: Live from Paris",
    "title_long": "The Big Steppers Tour: Live from Paris (2022)",
    "slug": "the-big-steppers-tour-live-from-paris-2022",
    "year": 2022,
    "rating": 8.5,
    "runtime": 112,
    "genres": [
      "Music"
    ],
    "summary": "The Big Steppers Tour is the fifth concert tour by Kendrick Lamar, in support of his album, Mr. Morale and the Big Steppers. Baby Keem and Tanna Leone serve as the opening acts",
    "description_full": "The Big Steppers Tour is the fifth concert tour by Kendrick Lamar, in support of his album, Mr. Morale and the Big Steppers. Baby Keem and Tanna Leone serve as the opening acts",
    "synopsis": "The Big Steppers Tour is the fifth concert tour by Kendrick Lamar, in support of his album, Mr. Morale and the Big Steppers. Baby Keem and Tanna Leone serve as the opening acts",
    "yt_trailer_code": "ayGI1pg2wtM",
    "language": "en",
    "mpa_rating": "",
    "background_image": "https://yts.mx/assets/images/movies/the_big_steppers_tour_live_from_paris_2022/background.jpg",
    "background_image_original": "https://yts.mx/assets/images/movies/the_big_steppers_tour_live_from_paris_2022/background.jpg",
    "small_cover_image": "https://yts.mx/assets/images/movies/the_big_steppers_tour_live_from_paris_2022/small-cover.jpg",
    "medium_cover_image": "https://yts.mx/assets/images/movies/the_big_steppers_tour_live_from_paris_2022/medium-cover.jpg",
    "large_cover_image": "https://yts.mx/assets/images/movies/the_big_steppers_tour_live_from_paris_2022/large-cover.jpg",
    "state": "ok",
    "torrents": [
      {
        "url": "https://yts.mx/torrent/download/BF3E36D67D9C4A8877F1BB13A09BF0C43CEE2029",
        "hash": "BF3E36D67D9C4A8877F1BB13A09BF0C43CEE2029",
        "quality": "720p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 2,
        "peers": 0,
        "size": "1 GB",
        "size_bytes": 1073741824,
        "date_uploaded": "2022-10-23 19:44:33",
        "date_uploaded_unix": 1666547073
      },
      {
        "url": "https://yts.mx/torrent/download/DB732085B150C8226B8D02F2D36E55AB043D63BD",
        "hash": "DB732085B150C8226B8D02F2D36E55AB043D63BD",
        "quality": "1080p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 10,
        "peers": 1,
        "size": "1.86 GB",
        "size_bytes": 1997159793,
        "date_uploaded": "2022-10-23 20:58:02",
        "date_uploaded_unix": 1666551482
      }
    ],
    "date_uploaded": "2022-10-23 19:44:33",
    "date_uploaded_unix": 1666547073
  },
  {
    "id": 52370,
    "url": "https://yts.mx/movies/sista-2022",
    "imdb_code": "tt21206344",
    "title": "Sista",
    "title_english": "Sista",
    "title_long": "Sista (2022)",
    "slug": "sista-2022",
    "year": 2022,
    "rating": 8.8,
    "runtime": 94,
    "genres": [
      "Drama"
    ],
    "summary": "A struggling single mother faces her worst nightmare when the father of her children comes into their lives and completely steals their attention all for himself.",
    "description_full": "A struggling single mother faces her worst nightmare when the father of her children comes into their lives and completely steals their attention all for himself.",
    "synopsis": "A struggling single mother faces her worst nightmare when the father of her children comes into their lives and completely steals their attention all for himself.",
    "yt_trailer_code": "",
    "language": "en",
    "mpa_rating": "",
    "background_image": "https://yts.mx/assets/images/movies/sista_2022/background.jpg",
    "background_image_original": "https://yts.mx/assets/images/movies/sista_2022/background.jpg",
    "small_cover_image": "https://yts.mx/assets/images/movies/sista_2022/small-cover.jpg",
    "medium_cover_image": "https://yts.mx/assets/images/movies/sista_2022/medium-cover.jpg",
    "large_cover_image": "https://yts.mx/assets/images/movies/sista_2022/large-cover.jpg",
    "state": "ok",
    "torrents": [
      {
        "url": "https://yts.mx/torrent/download/83740DBFFA234C3973345B81A0974EA8E96A761B",
        "hash": "83740DBFFA234C3973345B81A0974EA8E96A761B",
        "quality": "720p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 4,
        "peers": 0,
        "size": "865.92 MB",
        "size_bytes": 907982930,
        "date_uploaded": "2023-05-30 23:08:22",
        "date_uploaded_unix": 1685480902
      },
      {
        "url": "https://yts.mx/torrent/download/2E48A64EBA57488A4F87235C667AF1588DD72D51",
        "hash": "2E48A64EBA57488A4F87235C667AF1588DD72D51",
        "quality": "1080p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 12,
        "peers": 1,
        "size": "1.57 GB",
        "size_bytes": 1685774664,
        "date_uploaded": "2023-05-31 00:13:33",
        "date_uploaded_unix": 1685484813
      }
    ],
    "date_uploaded": "2023-05-30 23:08:22",
    "date_uploaded_unix": 1685480902
  },
  {
    "id": 53142,
    "url": "https://yts.mx/movies/777-charlie-2022",
    "imdb_code": "tt7466810",
    "title": "777 Charlie",
    "title_english": "777 Charlie",
    "title_long": "777 Charlie (2022)",
    "slug": "777-charlie-2022",
    "year": 2022,
    "rating": 8.8,
    "runtime": 164,
    "genres": [
      "Adventure",
      "Comedy",
      "Drama"
    ],
    "summary": "The protagonist is stuck in a rut with his negative and lonely lifestyle and spends each day in the comfort of his loneliness. A pup named Charlie who is naughty and energetic which makes him complete contrast with the protagonists' character enters his life and gives him a new perspective towards it.",
    "description_full": "The protagonist is stuck in a rut with his negative and lonely lifestyle and spends each day in the comfort of his loneliness. A pup named Charlie who is naughty and energetic which makes him complete contrast with the protagonists' character enters his life and gives him a new perspective towards it.",
    "synopsis": "The protagonist is stuck in a rut with his negative and lonely lifestyle and spends each day in the comfort of his loneliness. A pup named Charlie who is naughty and energetic which makes him complete contrast with the protagonists' character enters his life and gives him a new perspective towards it.",
    "yt_trailer_code": "VS-XRkcyYrE",
    "language": "kn",
    "mpa_rating": "",
    "background_image": "https://yts.mx/assets/images/movies/777_charlie_2022/background.jpg",
    "background_image_original": "https://yts.mx/assets/images/movies/777_charlie_2022/background.jpg",
    "small_cover_image": "https://yts.mx/assets/images/movies/777_charlie_2022/small-cover.jpg",
    "medium_cover_image": "https://yts.mx/assets/images/movies/777_charlie_2022/medium-cover.jpg",
    "large_cover_image": "https://yts.mx/assets/images/movies/777_charlie_2022/large-cover.jpg",
    "state": "ok",
    "torrents": [
      {
        "url": "https://yts.mx/torrent/download/0ABB4094DF4A52ECCD0D4AABA85723D881A66BD6",
        "hash": "0ABB4094DF4A52ECCD0D4AABA85723D881A66BD6",
        "quality": "720p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 38,
        "peers": 4,
        "size": "1.47 GB",
        "size_bytes": 1578400481,
        "date_uploaded": "2023-07-10 21:24:38",
        "date_uploaded_unix": 1689017078
      },
      {
        "url": "https://yts.mx/torrent/download/81CFCF4131EBB0C5AB769D06E354B19B5542D5C9",
        "hash": "81CFCF4131EBB0C5AB769D06E354B19B5542D5C9",
        "quality": "1080p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "5.1",
        "seeds": 32,
        "peers": 3,
        "size": "3.02 GB",
        "size_bytes": 3242700308,
        "date_uploaded": "2023-07-10 22:58:41",
        "date_uploaded_unix": 1689022721
      }
    ],
    "date_uploaded": "2023-07-10 21:24:38",
    "date_uploaded_unix": 1689017078
  },
  {
    "id": 45962,
    "url": "https://yts.mx/movies/homecoming-the-road-to-mullingar-2022",
    "imdb_code": "tt22522256",
    "title": "Homecoming: The Road to Mullingar",
    "title_english": "Homecoming: The Road to Mullingar",
    "title_long": "Homecoming: The Road to Mullingar (2022)",
    "slug": "homecoming-the-road-to-mullingar-2022",
    "year": 2022,
    "rating": 8.8,
    "runtime": 60,
    "genres": [
      "Documentary",
      "Music"
    ],
    "summary": "Niall Horan left his hometown of Mullingar at 16 to join one of the biggest boybands of all time. Now, 12 years later, Niall is coming home - and he's bringing his best friend Lewis Capaldi along for the ride. In this exclusive film, the two global superstars embark on an epic Irish road trip before they wrap up their travels with a once in a lifetime gig in Mullingar. Expect standout performances, laugh out loud moments and a whole lot of Irish charm. It's time to see two of the biggest singer songwriters on the planet like you've never seen them before.",
    "description_full": "Niall Horan left his hometown of Mullingar at 16 to join one of the biggest boybands of all time. Now, 12 years later, Niall is coming home - and he's bringing his best friend Lewis Capaldi along for the ride. In this exclusive film, the two global superstars embark on an epic Irish road trip before they wrap up their travels with a once in a lifetime gig in Mullingar. Expect standout performances, laugh out loud moments and a whole lot of Irish charm. It's time to see two of the biggest singer songwriters on the planet like you've never seen them before.",
    "synopsis": "Niall Horan left his hometown of Mullingar at 16 to join one of the biggest boybands of all time. Now, 12 years later, Niall is coming home - and he's bringing his best friend Lewis Capaldi along for the ride. In this exclusive film, the two global superstars embark on an epic Irish road trip before they wrap up their travels with a once in a lifetime gig in Mullingar. Expect standout performances, laugh out loud moments and a whole lot of Irish charm. It's time to see two of the biggest singer songwriters on the planet like you've never seen them before.",
    "yt_trailer_code": "",
    "language": "en",
    "mpa_rating": "",
    "background_image": "https://yts.mx/assets/images/movies/homecoming_the_road_to_mullingar_2022/background.jpg",
    "background_image_original": "https://yts.mx/assets/images/movies/homecoming_the_road_to_mullingar_2022/background.jpg",
    "small_cover_image": "https://yts.mx/assets/images/movies/homecoming_the_road_to_mullingar_2022/small-cover.jpg",
    "medium_cover_image": "https://yts.mx/assets/images/movies/homecoming_the_road_to_mullingar_2022/medium-cover.jpg",
    "large_cover_image": "https://yts.mx/assets/images/movies/homecoming_the_road_to_mullingar_2022/large-cover.jpg",
    "state": "ok",
    "torrents": [
      {
        "url": "https://yts.mx/torrent/download/DF0471408D71BCC5C5DF85D3BE02BF8B173BAD41",
        "hash": "DF0471408D71BCC5C5DF85D3BE02BF8B173BAD41",
        "quality": "720p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 5,
        "peers": 0,
        "size": "425.56 MB",
        "size_bytes": 446232003,
        "date_uploaded": "2022-10-20 18:25:09",
        "date_uploaded_unix": 1666283109
      },
      {
        "url": "https://yts.mx/torrent/download/F413BD2C85D49C75650B8951C8B026B1AA45F3F1",
        "hash": "F413BD2C85D49C75650B8951C8B026B1AA45F3F1",
        "quality": "1080p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 4,
        "peers": 1,
        "size": "788.79 MB",
        "size_bytes": 827106263,
        "date_uploaded": "2022-10-20 18:54:50",
        "date_uploaded_unix": 1666284890
      }
    ],
    "date_uploaded": "2022-10-20 18:25:09",
    "date_uploaded_unix": 1666283109
  },
  {
    "id": 54009,
    "url": "https://yts.mx/movies/scrap-2022",
    "imdb_code": "tt10422486",
    "title": "Scrap",
    "title_english": "Scrap",
    "title_long": "Scrap (2022)",
    "slug": "scrap-2022",
    "year": 2022,
    "rating": 8.8,
    "runtime": 105,
    "genres": [
      "Action",
      "Drama"
    ],
    "summary": "",
    "description_full": "",
    "synopsis": "",
    "yt_trailer_code": "",
    "language": "en",
    "mpa_rating": "",
    "background_image": "https://yts.mx/assets/images/movies/scrap_2022/background.jpg",
    "background_image_original": "https://yts.mx/assets/images/movies/scrap_2022/background.jpg",
    "small_cover_image": "https://yts.mx/assets/images/movies/scrap_2022/small-cover.jpg",
    "medium_cover_image": "https://yts.mx/assets/images/movies/scrap_2022/medium-cover.jpg",
    "large_cover_image": "https://yts.mx/assets/images/movies/scrap_2022/large-cover.jpg",
    "state": "ok",
    "torrents": [
      {
        "url": "https://yts.mx/torrent/download/B39E41AC64238E5F73252E829324CC2E34EED45D",
        "hash": "B39E41AC64238E5F73252E829324CC2E34EED45D",
        "quality": "720p",
        "type": "bluray",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 15,
        "peers": 2,
        "size": "718.09 MB",
        "size_bytes": 752971940,
        "date_uploaded": "2023-08-07 18:54:47",
        "date_uploaded_unix": 1691427287
      },
      {
        "url": "https://yts.mx/torrent/download/F5F043FF840C8FB6D0CCCB4459563E7E8095B724",
        "hash": "F5F043FF840C8FB6D0CCCB4459563E7E8095B724",
        "quality": "1080p",
        "type": "bluray",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "5.1",
        "seeds": 23,
        "peers": 3,
        "size": "1.44 GB",
        "size_bytes": 1546188227,
        "date_uploaded": "2023-08-07 19:48:05",
        "date_uploaded_unix": 1691430485
      }
    ],
    "date_uploaded": "2023-08-07 18:54:47",
    "date_uploaded_unix": 1691427287
  },
  {
    "id": 49079,
    "url": "https://yts.mx/movies/a-bees-diary-2022",
    "imdb_code": "tt18309322",
    "title": "A Bee's Diary",
    "title_english": "A Bee's Diary",
    "title_long": "A Bee's Diary (2022)",
    "slug": "a-bees-diary-2022",
    "year": 2022,
    "rating": 8.8,
    "runtime": 0,
    "genres": [
      "Action",
      "Documentary"
    ],
    "summary": "Scientists are learning that each bee in a hive is an individual, with its own personality. Follows the circle of life of the honeybees.",
    "description_full": "Scientists are learning that each bee in a hive is an individual, with its own personality. Follows the circle of life of the honeybees.",
    "synopsis": "Scientists are learning that each bee in a hive is an individual, with its own personality. Follows the circle of life of the honeybees.",
    "yt_trailer_code": "",
    "language": "",
    "mpa_rating": "",
    "background_image": "https://yts.mx/assets/images/movies/a_bees_diary_2022/background.jpg",
    "background_image_original": "https://yts.mx/assets/images/movies/a_bees_diary_2022/background.jpg",
    "small_cover_image": "https://yts.mx/assets/images/movies/a_bees_diary_2022/small-cover.jpg",
    "medium_cover_image": "https://yts.mx/assets/images/movies/a_bees_diary_2022/medium-cover.jpg",
    "large_cover_image": "https://yts.mx/assets/images/movies/a_bees_diary_2022/large-cover.jpg",
    "state": "ok",
    "torrents": [
      {
        "url": "https://yts.mx/torrent/download/1EAD0803CA6F6791A2BF1A93319C3DB377022339",
        "hash": "1EAD0803CA6F6791A2BF1A93319C3DB377022339",
        "quality": "720p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 2,
        "peers": 0,
        "size": "406.12 MB",
        "size_bytes": 425847685,
        "date_uploaded": "2023-02-18 19:34:20",
        "date_uploaded_unix": 1676745260
      },
      {
        "url": "https://yts.mx/torrent/download/788BCD2F7513B08396FC7C9090A8CBE367F96301",
        "hash": "788BCD2F7513B08396FC7C9090A8CBE367F96301",
        "quality": "1080p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 4,
        "peers": 1,
        "size": "752.4 MB",
        "size_bytes": 788948582,
        "date_uploaded": "2023-02-18 20:05:15",
        "date_uploaded_unix": 1676747115
      }
    ],
    "date_uploaded": "2023-02-18 19:34:20",
    "date_uploaded_unix": 1676745260
  },
  {
    "id": 50644,
    "url": "https://yts.mx/movies/charlie-mackesy-the-boy-the-mole-the-fox-the-horse-and-me-2022",
    "imdb_code": "tt23869628",
    "title": "Charlie Mackesy: The Boy, the Mole, the Fox, the Horse and Me",
    "title_english": "Charlie Mackesy: The Boy, the Mole, the Fox, the Horse and Me",
    "title_long": "Charlie Mackesy: The Boy, the Mole, the Fox, the Horse and Me (2022)",
    "slug": "charlie-mackesy-the-boy-the-mole-the-fox-the-horse-and-me-2022",
    "year": 2022,
    "rating": 8.6,
    "runtime": 0,
    "genres": [
      "Documentary"
    ],
    "summary": "British artist and illustrator Charlie Mackesy discusses his life and the events that inspired his best-selling book \"The Boy, the Mole, the Fox and the Horse\".",
    "description_full": "British artist and illustrator Charlie Mackesy discusses his life and the events that inspired his best-selling book \"The Boy, the Mole, the Fox and the Horse\".",
    "synopsis": "British artist and illustrator Charlie Mackesy discusses his life and the events that inspired his best-selling book \"The Boy, the Mole, the Fox and the Horse\".",
    "yt_trailer_code": "",
    "language": "en",
    "mpa_rating": "",
    "background_image": "https://yts.mx/assets/images/movies/charlie_mackesy_the_boy_the_mole_the_fox_the_horse_and_me_2022/background.jpg",
    "background_image_original": "https://yts.mx/assets/images/movies/charlie_mackesy_the_boy_the_mole_the_fox_the_horse_and_me_2022/background.jpg",
    "small_cover_image": "https://yts.mx/assets/images/movies/charlie_mackesy_the_boy_the_mole_the_fox_the_horse_and_me_2022/small-cover.jpg",
    "medium_cover_image": "https://yts.mx/assets/images/movies/charlie_mackesy_the_boy_the_mole_the_fox_the_horse_and_me_2022/medium-cover.jpg",
    "large_cover_image": "https://yts.mx/assets/images/movies/charlie_mackesy_the_boy_the_mole_the_fox_the_horse_and_me_2022/large-cover.jpg",
    "state": "ok",
    "torrents": [
      {
        "url": "https://yts.mx/torrent/download/79F245A707593026F8EAE0836A26ED9A86AA4FA4",
        "hash": "79F245A707593026F8EAE0836A26ED9A86AA4FA4",
        "quality": "720p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 8,
        "peers": 14,
        "size": "552.79 MB",
        "size_bytes": 579642327,
        "date_uploaded": "2023-04-12 05:59:58",
        "date_uploaded_unix": 1681271998
      },
      {
        "url": "https://yts.mx/torrent/download/4EBE6EE3719ECFA45F5645BAC12533CB164FE232",
        "hash": "4EBE6EE3719ECFA45F5645BAC12533CB164FE232",
        "quality": "1080p",
        "type": "web",
        "is_repack": "0",
        "video_codec": "x264",
        "bit_depth": "8",
        "audio_channels": "2.0",
        "seeds": 9,
        "peers": 7,
        "size": "1 GB",
        "size_bytes": 1073741824,
        "date_uploaded": "2023-04-12 06:51:22",
        "date_uploaded_unix": 1681275082
      }
    ],
    "date_uploaded": "2023-04-12 05:59:58",
    "date_uploaded_unix": 1681271998
  }
]